site_name: MyHomeLab
site_url: https://myhomelab.co.in
theme:
  name: material
  palette:
    primary: black
  Plugin:
   -blog
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs


